name: .Net Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:
  workflow_call:

env:
  Solution_Name: getting-started.sln
  Test_Project_Path: DisplayTests

jobs:
  build:

    name: Build and Test
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Install ntools
      run: |
        cd ./DevSetup
        ./DevSetup.ps1
      shell: pwsh
      working-directory: ${{ github.workspace }}

    - name: Set ProgramFiles Path
      run: |
        $programFilesPath = [System.Environment]::GetFolderPath('ProgramFiles')
        echo "ProgramFilesPath=$programFilesPath" | Out-File -FilePath $env:GITHUB_ENV -Append
      shell: pwsh
      working-directory: ${{ github.workspace }}
   
    - name: Configure Git
      run: |
        git config --global user.name "gitHub-actions"
        git config --global user.email "actions@github.com"

    - name: Build using ntools
      run: |
        & "$env:ProgramFilesPath/nbuild/nb.exe" solution
      shell: pwsh
      working-directory: ${{ github.workspace }}

    - name: Test using ntools
      run: |
        & "$env:ProgramFilesPath/nbuild/nb.exe" test
      shell: pwsh
      working-directory: ${{ github.workspace }}
